### ISSUE TITLE
makeTFfasta requires uncompressed gff

### ISSUE THREAD

**Issue by goeringr** [TaliaferroLab/LABRAT#1]
```
[goeringr@compute00 mmGtexLABRAT]$ python LABRAT.py --mode makeTFfasta --gff ~/Annotations/mm10/gencode.vM23.annotation.gff3.gz --genomefasta ~/Annotations/mm10/GRCm38.p6.genome.fa.gz --lasttwoexons

/beevol/home/goeringr/.conda/envs/labrat/lib/python3.6/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
Indexing gff...
Traceback (most recent call last):
  File "LABRAT.py", line 659, in <module>
    makeTFfasta(args.gff, args.genomefasta, args.lasttwoexons)
  File "LABRAT.py", line 254, in makeTFfasta
    db = gffutils.FeatureDB(db_fn)
  File "/beevol/home/goeringr/.conda/envs/labrat/lib/python3.6/site-packages/gffutils/interface.py", line 132, in __init__
    version, dialect = c.fetchone()
TypeError: 'NoneType' object is not iterable
```
unzipping the gff resolves this issue

**Comment by taliaferrojm** [comment]
Because gffutils requires a filepath to the gff and not simply a file object, there doesn't seem to be a suitable way to resolve this without just having LABRAT unzip the gff itself. I don't love this option because these can be big files, and the user might want to have more explicit control over what is happening with them.

For now, I just added explicit instructions to the documentation that the gff annotation must not be compressed.
